POST http://localhost:4000/api/trades/buy
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGY4YTMxZmQ3OWRlZjk3YmVkYzEyYTgiLCJlbWFpbCI6InZpcmF0QGdtYWlsLmNvbSIsImlhdCI6MTc2MTE5NTAxMCwiZXhwIjoxNzYxMjgxNDEwfQ.gSB4ytnmpqg6W9MN2SMujh3zB9n0P2v7xi0Bev8GUA4
{
  "symbol": "AAPL",
  "quantity": 8
}
