GET http://localhost:4000/api/trades
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGY4YTMxZmQ3OWRlZjk3YmVkYzEyYTgiLCJlbWFpbCI6InZpcmF0QGdtYWlsLmNvbSIsImlhdCI6MTc2MTIwMjkzNywiZXhwIjoxNzYxMjg5MzM3fQ.FBj_A0SGPISIn04-l7jY0-INBKWeOmefEBMzA7PlnTE