GET http://localhost:4000/api/portfolio
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGY4YTMxZmQ3OWRlZjk3YmVkYzEyYTgiLCJlbWFpbCI6InZpcmF0QGdtYWlsLmNvbSIsImlhdCI6MTc2MTI3ODE5OSwiZXhwIjoxNzYxMzY0NTk5fQ.F1-aTb31xHUCa83IVNUfu7-joQvLgJ1jHvO56UqlvD8
